apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: checkout-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: checkoutservice
        namespace: apm-beverages
      spec:
        type: ClusterIP
        selector:
          app: checkoutservice
        ports:
          - name: grpc
            port: 5050
            targetPort: 5050
  providerConfigRef:
    name: kube-config