apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: loadgenerator-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        name: loadgenerator
        namespace: apm-beverages
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "5"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "3"
          service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "2"
          external-dns.alpha.kubernetes.io/hostname: demo-load.
      spec:
        type: LoadBalancer
        selector:
          app: loadgenerator
        ports:
          - name: http
            port: 82
            targetPort: 8089
  providerConfigRef:
    name: kube-config