apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: APM-Beverages
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Namespace
      metadata:
        # name in manifest is optional and defaults to Object name
        labels:
          example: "true"
  providerConfigRef:
    name: kube-config