kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: okta-ns-admin1
  namespace: demo1
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: okta-kubernetes-OIDC
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: okta-admin1
