apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: sample-nginx-service
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: Service
      metadata:
        # name in manifest is optional and defaults to Object name
        name: nginx-service
        namespace: nginx-namespace
      spec:
        selector:
         app: nginx
        ports:
        - port: 80
          protocol: TCP
          targetport: 80
  providerConfigRef:
    name: kube-config